import type {
  AccessibleCustomerDetail,
  AccessibleCustomerListItem,
  AccessibleUnlinkedCustomerCase,
} from '@/lib/data/store';

const YAMADA_DETAIL: AccessibleCustomerDetail = {
  customer: {
    id: 'demo-customer-yamada',
    customer_no: 'DEMO-0001',
    full_name: '山田 太郎',
    company_name: '株式会社サンプル住建',
    email: 'demo.yamada@example.com',
    phone: '000-1111-2222',
    postal_code: '000-0000',
    address: '石川県鳳珠郡穴水町 サンプル1-1',
    created_at: '2026-07-10T01:00:00.000Z',
  },
  latest_contact: {
    full_name: '山田 太郎',
    company_name: '株式会社サンプル住建',
    email: 'demo.yamada@example.com',
    phone: '000-1111-2222',
    address: '石川県鳳珠郡穴水町 サンプル1-1',
    site_address: '石川県鳳珠郡穴水町（設置予定地サンプル）',
  },
  cases: [
    {
      id: 'demo-case-yamada-1',
      request_status: 'reviewing',
      message: '宿泊棟として検討中。現地確認後に仕様を確定予定。',
      contact: {
        full_name: '山田 太郎',
        company_name: '株式会社サンプル住建',
        email: 'demo.yamada@example.com',
        phone: '000-1111-2222',
        address: '石川県鳳珠郡穴水町 サンプル1-1',
        site_address: '石川県鳳珠郡穴水町（設置予定地サンプル）',
      },
      site_address: '石川県鳳珠郡穴水町（設置予定地サンプル）',
      site_source: 'quote_contact',
      ongoing: true,
      activity_at: '2026-09-28T06:30:00.000Z',
      model_name: 'Wing',
      dealer_name: '能登 太郎',
      dealer_company: 'サンプル代理店株式会社',
      open_quote_id: 'demo-quote-yamada-2',
      latest_quote: {
        id: 'demo-quote-yamada-2',
        case_id: 'demo-case-yamada-1',
        quote_no: 'W-DEMO-0001',
        revision: 2,
        status: 'issued',
        base_model_name: 'Wing',
        issued_at: '2026-09-28T06:00:00.000Z',
        total: 5280000,
        can_open_quote: false,
      },
    },
    {
      id: 'demo-case-yamada-2',
      request_status: 'closed',
      message: '離れ客室として過去に検討した案件。',
      contact: {
        full_name: '山田 太郎',
        company_name: '株式会社サンプル住建',
        email: 'demo.yamada@example.com',
        phone: '000-1111-2222',
        address: '石川県鳳珠郡穴水町 サンプル1-1',
        site_address: '石川県輪島市（過去案件サンプル）',
      },
      site_address: '石川県輪島市（過去案件サンプル）',
      site_source: 'quote_contact',
      ongoing: false,
      activity_at: '2026-06-18T03:00:00.000Z',
      model_name: 'PLUS',
      dealer_name: '能登 太郎',
      dealer_company: 'サンプル代理店株式会社',
      open_quote_id: null,
      latest_quote: {
        id: 'demo-quote-yamada-old',
        case_id: 'demo-case-yamada-2',
        quote_no: 'P-DEMO-0004',
        revision: 1,
        status: 'declined',
        base_model_name: 'PLUS',
        issued_at: '2026-06-15T02:00:00.000Z',
        total: 2650000,
        can_open_quote: false,
      },
    },
  ],
  quote_history: [
    {
      id: 'demo-quote-yamada-2',
      case_id: 'demo-case-yamada-1',
      quote_no: 'W-DEMO-0001',
      revision: 2,
      status: 'issued',
      base_model_name: 'Wing',
      issued_at: '2026-09-28T06:00:00.000Z',
      total: 5280000,
      can_open_quote: false,
    },
    {
      id: 'demo-quote-yamada-1',
      case_id: 'demo-case-yamada-1',
      quote_no: 'W-DEMO-0001',
      revision: 1,
      status: 'superseded',
      base_model_name: 'Wing',
      issued_at: '2026-09-20T05:00:00.000Z',
      total: 5100000,
      can_open_quote: false,
    },
    {
      id: 'demo-quote-yamada-old',
      case_id: 'demo-case-yamada-2',
      quote_no: 'P-DEMO-0004',
      revision: 1,
      status: 'declined',
      base_model_name: 'PLUS',
      issued_at: '2026-06-15T02:00:00.000Z',
      total: 2650000,
      can_open_quote: false,
    },
  ],
};

const SATO_DETAIL: AccessibleCustomerDetail = {
  customer: {
    id: 'demo-customer-sato',
    customer_no: 'DEMO-0002',
    full_name: '佐藤 花子',
    company_name: null,
    email: 'demo.sato@example.com',
    phone: '000-3333-4444',
    postal_code: '000-0000',
    address: '石川県珠洲市 サンプル2-2',
    created_at: '2026-05-02T01:00:00.000Z',
  },
  latest_contact: {
    full_name: '佐藤 花子',
    company_name: null,
    email: 'demo.sato@example.com',
    phone: '000-3333-4444',
    address: '石川県珠洲市 サンプル2-2',
    site_address: null,
  },
  cases: [
    {
      id: 'demo-case-sato-1',
      request_status: 'closed',
      message: '小規模事務所用途で検討した過去案件。',
      contact: {
        full_name: '佐藤 花子',
        company_name: null,
        email: 'demo.sato@example.com',
        phone: '000-3333-4444',
        address: '石川県珠洲市 サンプル2-2',
        site_address: null,
      },
      site_address: null,
      site_source: null,
      ongoing: false,
      activity_at: '2026-08-04T04:20:00.000Z',
      model_name: 'BOX',
      dealer_name: '奥能登 次郎',
      dealer_company: 'サンプル建築販売',
      open_quote_id: null,
      latest_quote: {
        id: 'demo-quote-sato-1',
        case_id: 'demo-case-sato-1',
        quote_no: 'B-DEMO-0012',
        revision: 1,
        status: 'declined',
        base_model_name: 'BOX',
        issued_at: '2026-07-30T04:00:00.000Z',
        total: 3980000,
        can_open_quote: false,
      },
    },
  ],
  quote_history: [
    {
      id: 'demo-quote-sato-1',
      case_id: 'demo-case-sato-1',
      quote_no: 'B-DEMO-0012',
      revision: 1,
      status: 'declined',
      base_model_name: 'BOX',
      issued_at: '2026-07-30T04:00:00.000Z',
      total: 3980000,
      can_open_quote: false,
    },
  ],
};

const SUZUKI_DETAIL: AccessibleCustomerDetail = {
  customer: {
    id: 'demo-customer-suzuki',
    customer_no: 'DEMO-0003',
    full_name: '鈴木 一郎',
    company_name: '能登企画サンプル株式会社',
    email: 'demo.suzuki@example.com',
    phone: null,
    postal_code: null,
    address: '石川県羽咋市 サンプル3-3',
    created_at: '2026-09-01T01:00:00.000Z',
  },
  latest_contact: {
    full_name: '鈴木 一郎',
    company_name: '能登企画サンプル株式会社',
    email: 'demo.suzuki@example.com',
    phone: '',
    address: '石川県羽咋市 サンプル3-3',
    site_address: '未定',
  },
  cases: [
    {
      id: 'demo-case-suzuki-1',
      request_status: 'new',
      message: '店舗利用を想定。設置予定地は未定。',
      contact: {
        full_name: '鈴木 一郎',
        company_name: '能登企画サンプル株式会社',
        email: 'demo.suzuki@example.com',
        phone: '',
        address: '石川県羽咋市 サンプル3-3',
        site_address: null,
      },
      site_address: '未定',
      site_source: 'configuration',
      ongoing: true,
      activity_at: '2026-09-29T03:15:00.000Z',
      model_name: 'Wing',
      dealer_name: null,
      dealer_company: null,
      open_quote_id: null,
      latest_quote: null,
    },
  ],
  quote_history: [],
};

export const DEMO_CUSTOMER_DETAILS: AccessibleCustomerDetail[] = [
  YAMADA_DETAIL,
  SATO_DETAIL,
  SUZUKI_DETAIL,
];

export const DEMO_CUSTOMERS: AccessibleCustomerListItem[] = [
  {
    id: YAMADA_DETAIL.customer.id,
    customer_no: YAMADA_DETAIL.customer.customer_no,
    full_name: YAMADA_DETAIL.customer.full_name,
    company_name: YAMADA_DETAIL.customer.company_name,
    email: YAMADA_DETAIL.customer.email,
    phone: YAMADA_DETAIL.customer.phone,
    address: YAMADA_DETAIL.customer.address,
    ongoing_case_count: 1,
    recent_case: {
      id: 'demo-case-yamada-1',
      open_quote_id: null,
      quote_no: 'W-DEMO-0001',
      model_name: 'Wing',
      site_address: '石川県鳳珠郡穴水町（設置予定地サンプル）',
      activity_at: '2026-09-28T06:30:00.000Z',
      dealer_name: '能登 太郎',
    },
  },
  {
    id: SUZUKI_DETAIL.customer.id,
    customer_no: SUZUKI_DETAIL.customer.customer_no,
    full_name: SUZUKI_DETAIL.customer.full_name,
    company_name: SUZUKI_DETAIL.customer.company_name,
    email: SUZUKI_DETAIL.customer.email,
    phone: SUZUKI_DETAIL.customer.phone,
    address: SUZUKI_DETAIL.customer.address,
    ongoing_case_count: 1,
    recent_case: {
      id: 'demo-case-suzuki-1',
      open_quote_id: null,
      quote_no: null,
      model_name: 'Wing',
      site_address: '未定',
      activity_at: '2026-09-29T03:15:00.000Z',
      dealer_name: null,
    },
  },
  {
    id: SATO_DETAIL.customer.id,
    customer_no: SATO_DETAIL.customer.customer_no,
    full_name: SATO_DETAIL.customer.full_name,
    company_name: SATO_DETAIL.customer.company_name,
    email: SATO_DETAIL.customer.email,
    phone: SATO_DETAIL.customer.phone,
    address: SATO_DETAIL.customer.address,
    ongoing_case_count: 0,
    recent_case: {
      id: 'demo-case-sato-1',
      open_quote_id: null,
      quote_no: 'B-DEMO-0012',
      model_name: 'BOX',
      site_address: null,
      activity_at: '2026-08-04T04:20:00.000Z',
      dealer_name: '奥能登 次郎',
    },
  },
];

export const DEMO_UNLINKED_CASES: AccessibleUnlinkedCustomerCase[] = [
  {
    id: 'demo-unlinked-case-1',
    full_name: '高橋 美咲',
    company_name: 'サンプル商事株式会社',
    identity_issue: 'missing_profile',
    open_quote_id: null,
    quote_no: 'W-DEMO-0099',
    model_name: 'Wing',
    site_address: '石川県能登町（サンプル）',
    activity_at: '2026-09-27T07:00:00.000Z',
    dealer_name: '奥能登 次郎',
  },
];

export function getDemoCustomerDetail(id: string): AccessibleCustomerDetail | null {
  return DEMO_CUSTOMER_DETAILS.find((detail) => detail.customer.id === id) ?? null;
}
